### ISSUE TITLE
[Bug] Hook fails to properly retract on death (Hookshot Hovering)

### ISSUE THREAD

**Issue by TaiNoire** [Adventurecraft-Awakening/AC-Legacy-Mod#25]
Dying while being hooked to a block and letting the hook retract before respawning will keep the player in a "hooked" state.

https://user-images.githubusercontent.com/67268889/231872244-68d399a4-7034-4ba9-8cc6-a7e94aaace27.mp4

**Comment by RyuuSlayer** [comment]
Fix merged from Kiroto.
