### ISSUE TITLE
[Bug] Hookshot Hand breaks when relogging

### ISSUE THREAD

**Issue by TaiNoire** [Adventurecraft-Awakening/AC-Legacy-Mod#26]
Relogging while a hookshot is being fired will cause the player to be unable to shoot the hookshot from the hand it was originally fired from.

Restarting the game fixes the issue.

https://user-images.githubusercontent.com/67268889/231872802-65f173c2-9ee6-4080-896d-5a91f6d54281.mp4

**Comment by RyuuSlayer** [comment]
Fix merged from Kiroto.
