### ISSUE TITLE
[Bug] Light Value changes wont load / apply until debug mode has been entered once every load

### ISSUE THREAD

**Issue by Gordon-Neb** [Adventurecraft-Awakening/AC-Legacy-Mod#33]
If the light values have been changed via /config command and saved they will reset to default on map loading and only change back if the player enters debug mode at least once so the player would need to do it every time the he loads the map.

**Comment by TechPizzaDev** [comment]
Hopefully fixed with https://github.com/Adventurecraft-Awakening/AC-Legacy-Mod/commit/5e7d2e528c0bd8dc7e5cc84669beec9c3e6ebe1f and https://github.com/Adventurecraft-Awakening/AC-Legacy-Mod/commit/51e133495521a47c1d8e48fc16d9053cc8dd7f36
