### ISSUE TITLE
[Bug] Naturally occurring rain 

### ISSUE THREAD

**Issue by MartinMclellan** [Adventurecraft-Awakening/AC-Legacy-Mod#34]
It appears naturally occurring rain was left on. While it can be worked around using scripts, natural rain wasn't a thing in the original AdventureCraft

**Comment by TechPizzaDev** [comment]
Should be fixed with https://github.com/Adventurecraft-Awakening/AC-Legacy-Mod/commit/f9c509a75b411f0b0a0611f627156f5c5248d64c
