### ISSUE TITLE
[Regression] Guns do not deal damage

### ISSUE THREAD

**Issue by GameBaseSFM** [Adventurecraft-Awakening/AC-Legacy-Mod#40]
All of the guns can be equipped and used, but do not have an effect on enemies at all

**Comment by TechPizzaDev** [comment]
Was a silly issue introduced by removing a copy to a seemingly non-mutating method. 

https://github.com/Adventurecraft-Awakening/AC-Legacy-Mod/commit/ce0805dea94b9756c11a029bc91b742fc45002b0#diff-8e513dce28ac40b4067b9522b1834e56a3975aa5693f16a6134a4634eb022dc1L52-R58
