### ISSUE TITLE
[bug] Gun not working, missing sound effect

### ISSUE THREAD

**Issue by DarioStar03** [Adventurecraft-Awakening/AC-Legacy-Mod#50]
I've played a very old map, "The Dam", and the guns didn't work, and didn't do any sound effects, along with the sound effect of placing tnt. and the cutscene was very buggy

**Comment by TechPizzaDev** [comment]
Gun damage [was already fixed](https://github.com/Adventurecraft-Awakening/AC-Legacy-Mod/issues/40#issuecomment-1666642748), but sounds are still missing in the launcher.

**Comment by DarioStar03** [comment]
> Gun damage [was already fixed](https://github.com/Adventurecraft-Awakening/AC-Legacy-Mod/issues/40#issuecomment-1666642748), but sounds are still missing in the launcher.

guns still do no damage for me, am I missing an update?

**Comment by TechPizzaDev** [comment]
It is not released in the launcher yet. I kept this issue open for the sound effect issues.

**Comment by TechPizzaDev** [comment]
Fixed with https://github.com/Adventurecraft-Awakening/AC-Legacy-Mod/commit/9fbdf461e338eee1a6692a6da17852348cce0bc9 and https://github.com/Adventurecraft-Awakening/AC-Legacy-Mod/commit/014ea5b0e847a222b19c40b7f84e7939664a3865
