### ISSUE TITLE
[Bug] Assets do not get de/reloaded correctly when changing between different maps

### ISSUE THREAD

**Issue by wjg999** [Adventurecraft-Awakening/AC-Legacy-Mod#58]
Playing one map and then opening another causes the assets of both to mash together.
An example of this is playing Solid Weapon and then Zelda Adventure.
Solid Weapon changes the door open/close sounds and some of the bomb explosion noises, this persists when playing another map.

**Comment by TechPizzaDev** [comment]
Fixed by https://github.com/Adventurecraft-Awakening/AC-Legacy-Mod/commit/1b0d817358764df2df7dcb8740a6b013556a0b73
