### ISSUE TITLE
Paste Tool no longer gets affected by CTRL-Z CTRL-Y

### ISSUE THREAD

**Issue by MartinMclellan** [Adventurecraft-Awakening/AC-Legacy-Mod#68]
When using the paste tool to place blocks, the blocks that are placed are not affected by undo and redo.

**Comment by TechPizzaDev** [comment]
Fixed by https://github.com/Adventurecraft-Awakening/AC-Legacy-Mod/commit/8e2062142379458627bb044fb5c16015e9311309 and https://github.com/Adventurecraft-Awakening/AC-Legacy-Mod/commit/eb650b75d719582c63e4e8737b45ac9f33f49e4f
